name: bootstrap_typography2_example
description: Bootstrap typography example
version: 1.0.2

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bootstrap_typography2:
    path: ../
  flutter:
    sdk: flutter

flutter:

