name: bootstrap_typography2
description: Bootstrap typography, size text based on screen size, uses bootstrap values in pixels
version: 2.0.0
repository: https://github.com/Honeyman-Applications/bootstrap_typography2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bootstrap_like_breakpoints: ^0.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true