name: bootstrap_typography2
description: Bootstrap typography, size text based on screen size, uses bootstrap values in pixels
version: 1.2.2
homepage: https://pub.dev/packages/bootstrap_typography2
repository: https://github.com/Honeyman-Applications/bootstrap_typography2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bootstrap_like_breakpoints: ^0.2.0
  flutter:
    sdk: flutter

flutter:

